name: school_track
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0-81.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.1.0
  ferry: ^0.15.0+1
  ferry_flutter: ^0.9.0
  gql_http_link: ^1.0.1+1
  cupertino_icons: ^1.0.6

dev_dependencies:
  build_runner: ^2.4.8
  ferry_generator: ^0.9.1-dev.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
